### ISSUE TITLE
 Showing All Errors Only node_modules/react-native-telink-ble/ios/DemoCommand.h:41:9: 'TelinkSigMeshLib/TelinkSigMeshLib.h' file not found with <angled> include; use "quotes" instead

### ISSUE THREAD

**Issue by daihieptn97** [thanhtunguet/react-native-telink-ble#3]
Mình  đã làm theo hướng dẫn và đang gặp lỗi này, 
Proeject mình đã có file -Bridging-Header.h

![image](https://user-images.githubusercontent.com/26356335/209260918-9750336c-10b7-430a-b9d9-9e3fe21a4621.png)

Có cách nào khắc phục không? 
Cảm ơn bạn!

**Comment by thanhtunguet** [comment]
> Mình đã làm theo hướng dẫn và đang gặp lỗi này, Proeject mình đã có file -Bridging-Header.h
> 
> ![image](https://user-images.githubusercontent.com/26356335/209260918-9750336c-10b7-430a-b9d9-9e3fe21a4621.png)
> 
> Có cách nào khắc phục không? Cảm ơn bạn!

Có vẻ hướng dẫn mình viết thiếu

Bạn thử thêm 2 dòng sau vào Podfile nhé:

```Podfile
  pod "TelinkSigMeshLib",        :path => "../node_modules/react-native-telink-ble"
  pod "react-native-telink-ble", :path => "../node_modules/react-native-telink-ble"
```

**Comment by daihieptn97** [comment]
> > Mình đã làm theo hướng dẫn và đang gặp lỗi này, Proeject mình đã có file -Bridging-Header.h
> > ![image](https://user-images.githubusercontent.com/26356335/209260918-9750336c-10b7-430a-b9d9-9e3fe21a4621.png)
> > Có cách nào khắc phục không? Cảm ơn bạn!
> 
> Có vẻ hướng dẫn mình viết thiếu
> 
> Bạn thử thêm 2 dòng sau vào Podfile nhé:
> 
> ```
>   pod "TelinkSigMeshLib",        :path => "../node_modules/react-native-telink-ble"
>   pod "react-native-telink-ble", :path => "../node_modules/react-native-telink-ble"
> ```


Mình cảm ơn nhé, nó chạy rồi :v
